on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}
      - uses: rubygems/release-gem@v1
        if: ${{ steps.release.outputs.release_created }}
